import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";


const inter = Inter({
  subsets: ["latin"],
  display: 'swap'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
        >
        <main className="container w-11/12 mx-auto">
        <Navbar></Navbar>
        {children}
        </main>
      </body>
    </html>
  );
}
